### ISSUE TITLE
Channel value class does not support megaphone.fm feeds

### ISSUE THREAD

**Issue by bencarrr** [phanan/poddle#5]
There is an issue with megaphone.fm RSS feeds because they do not include the `channel->link` property so calling `getChannel()` fails because the Channel class requires a link (like the RSS 2.0 spec, as it should)

Megaphone (by Spotify) is like 35%+ market share of podcasts so its a reasonably sized use case for this to be considered as an issue.

Example: https://feeds.megaphone.fm/GLT1412515089

PS: 🖕Spotify

**Comment by phanan** [comment]
Not sure I follow. In the example you give, there's an `<atom:link>` element inside `<channel>`, no?

**Comment by phanan** [comment]
I've attempted a fix. Do you think you can give it a try?
